-- Insert admin user (password: Admin@123)
-- Note: Use the actual BCrypt hash generated by your application
IF NOT EXISTS (SELECT * FROM users WHERE email = 'admin@brewnest.com')
BEGIN
    INSERT INTO users (email, password, full_name, phone_number, role, is_active) 
    VALUES ('admin@brewnest.com', '$2a$10$rQxGqZzZzZzZzZzZzZzZzO7LqXqXqXqXqXqXqXqXqXqXqXqXqXq', 'System Administrator', '9876543210', 'ADMIN', 1);
END
GO

-- Insert sample customer (optional - for testing)
IF NOT EXISTS (SELECT * FROM users WHERE email = 'customer@example.com')
BEGIN
    INSERT INTO users (email, password, full_name, phone_number, role, is_active) 
    VALUES ('customer@example.com', '$2a$10$dummyHashForTesting123456789012345678901234567890', 'Sample Customer', '1234567890', 'CUSTOMER', 1);
END
GO